version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: lk
      POSTGRES_USER: lk_user
      POSTGRES_PASSWORD: lk_pass
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    env_file: ./.env
    volumes:
      - ./backend:/app         
    environment:
      - PYTHONPATH=/app
    depends_on: [db]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  web:
    build:
      context: ./frontend
      target: dev                 
    command: npm run dev -- --host
    ports: ["5173:5173"]
    volumes:
      - ./frontend:/app             
      - /app/node_modules 
    depends_on: [api]

volumes:
  pgdata:
  minio_data:
